# Generated by Django 6.0.5 on 2026-05-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reader',
                'verbose_name_plural': 'Readers',
                'ordering': ['full_name'],
            },
        ),
    ]
