# Generated by Django 6.0.5 on 2026-05-31 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, default='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_details', to='biblioteca.book')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='biblioteca.loan')),
            ],
            options={
                'verbose_name': 'Loan Detail',
                'verbose_name_plural': 'Loan Details',
                'ordering': ['id'],
            },
        ),
    ]
